plc:
  pregrasp_tcp: ns=3;s="GP7_Local"."PreGrasp"."TCPPosition"
  wrist_rotate_tcp: ns=3;s="GP7_Local"."WristRotation"."TCPPosition"
  approach_tcp: ns=3;s="GP7_Local"."Approach"."TCPPosition"
  state_motion: ns=3;s="GP7_DynamicMotion_DB"."state_motion"
  state_start: ns=3;s="GP7_DynamicMotion_DB"."state_start"
  get_6D_pose_data: ns=3;s="GP7_get_6D_pose_data"
  point_to_marker: ns=3;s="GP7_Local"."Point_to_Marker"."TCPPosition"
  right_to_left: ns=3;s="GP7_Local"."Right_to_Left"."TCPPosition"
  bUp: ns=3;s="RE_button_mapping_DB"."bUp"
  bDown: ns=3;s="RE_button_mapping_DB"."bDown"
  bLeft: ns=3;s="RE_button_mapping_DB"."bLeft"
  bRight: ns=3;s="RE_button_mapping_DB"."bRight"
  bFindEdge: ns=3;s="RE_button_mapping_DB"."bFindEdge"
